defaults:
  - penalizer/lagrangian

name: lambda
replay_buffer:
  batch_size: 32
  sequence_length: 50
  capacity: 1000
model:
  hidden_size: 200
  stochastic_size: 60
  deterministic_size: 200
actor:
  n_layers: 3
  hidden_size: 400
  init_stddev: 5.
critic:
  n_layers: 3
  hidden_size: 400
actor_optimizer:
  lr: 8e-5
  eps: 1e-5
  clip: 0.5
critic_optimizer:
  lr: 8e-5
  eps: 1e-5
  clip: 0.5
safety_critic_optimizer:
  lr: 8e-5
  eps: 1e-5
  clip: 0.5
model_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
discount: 0.99
safety_discount: 0.99
lambda_: 0.97
plan_horizon: 15
update_steps: 20
train_every: 4
beta: 1.0
free_nats: 1.
safety_slack: 1.
