defaults:
  - _self_
  - agent: la_mbda
  - environment: dm_cartpole

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.override_dirname}/seed=${training.seed}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - training.seed
          - wandb_notes
    chdir: true

log_dir: outputs

writers:
  - wandb
  - jsonl
  - stderr

wandb:
  group: null
  notes: null
  name: null

jit: true

training:
  safe: true
  safety_budget: 100
  seed: 0
  time_limit: 1000
  episodes_per_epoch: 10
  eval_episodes: 10
  epochs: 200
  action_repeat: 1
  render_episodes: 1
  precision: 32
  parallel_envs: 20
  scale_reward: 1.
